apiVersion: v1
kind: ConfigMap
metadata:
  namespace: volodymyr
  name: nginx-config
data:
  default.conf.template: |
    server {
        listen 8080;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
