apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtYWh6aSIsInBhc3N3b3JkIjoiUHNBUTlmNTMlVmpNdk55akJrbkYiLCJlbWFpbCI6InN0ZWFtdXM1MDBAZ21haWwuY29tIiwiYXV0aCI6ImJXRm9lbWs2VUhOQlVUbG1OVE1sVm1wTmRrNTVha0pyYmtZPSJ9fX0=
kind: Secret
metadata:
  name: registry-auth
  namespace: volodymyr
type: kubernetes.io/dockerconfigjson
