Vagrant.configure("2") do |config|
    config.vm.define "jenkins" do |jenkins|
        jenkins.vm.box = "bento/ubuntu-22.04"
        jenkins.vm.hostname = "Jenkins"
        jenkins.vm.synced_folder "D:\\Study\\DanIT\\Second_step_project\\jenkins_home","/home/vagrant/jenkins_home"
      
        jenkins.vm.network "private_network", type: "dhcp"
        jenkins.vm.provider "vmware_desktop" do |v|
            v.memory = 1024
            v.cpus = 2
        end
  
    jenkins.vm.provision "shell", inline: <<-SHELL
        # Docker installation
        # Add Docker's official GPG key:
        apt-get install ca-certificates curl
        apt-get update
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        chmod a+r /etc/apt/keyrings/docker.asc

        # Add the repository to Apt sources:
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        # Create docker-compose.yml
        echo -e "
version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - /home/vagrant/jenkins_home:/var/jenkins_home
        
volumes:
  jenkins-home:" > docker-compose.yml
        # Start Jenkins
        mkdir jenkins_home  
        chmod 777 jenkins_home
        docker compose up -d
        SHELL
        end

    # Create Agent vm
    config.vm.define "agent" do |agent|
        agent.vm.box = "bento/ubuntu-22.04"
        agent.vm.hostname = "agent"
          
        agent.vm.network "private_network", type: "dhcp"
        agent.vm.provider "virtualbox" do |v|
            v.memory = 1024
            v.cpus = 2
        end

    agent.vm.provision "shell", inline: <<-SHELL
        # Docker installation
        # Add Docker's official GPG key:
        apt-get install ca-certificates curl
        apt-get update
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        chmod a+r /etc/apt/keyrings/docker.asc

        # Add the repository to Apt sources:
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        # Install JDK, ovpenssh-server and git
        apt-get install -y default-jdk openssh-server git
        # Install Node.js and npm
        apt-get install nodejs npm
        SHELL
        end
    end
  