apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: volodymyr
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # volumes:
      #   - name: nginx-storage
      #     persistentVolumeClaim:
      #       claimName: nginx-pvc
      containers:
      - name: nginx
        image: mahzi/flask-web-server
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        # volumeMounts:
        #   - mountPath: "/usr/share/nginx/html"
        #     name: nginx-storage
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      nodeSelector:
        beta.kubernetes.io/os: linux
        beta.kubernetes.io/arch: amd64
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nginx-pvc
#   namespace: volodymyr
# spec:
#   storageClassName: gp2
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 3Gi
  # volumeName: foo-pv
