apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: volodymyr
spec:
  selector:
    app: nginx
  type: LoadBalancer
  # sessionAffinity: ClientIP
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30008
