all:
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: id_rsa_lector
  children:
    observer:
      hosts:
        padok-observer:
          ansible_host: 16.171.60.168
    target:
      hosts:
        padok-observer:
          ansible_host: 16.171.60.168
        padok-target-1:
          ansible_host: 16.171.145.87
        padok-target-2:
          ansible_host: 13.50.231.73
